EVENT_ABILITY_COOLDOWN_UPDATED = 111 --- (*integer* _abilityId_)
EVENT_ABILITY_LIST_CHANGED = 111 
EVENT_ABILITY_PROGRESSION_RANK_UPDATE = 111 --- (*luaindex* _progressionIndex_, *integer* _rank_, *integer* _maxRank_, *integer* _morph_)
EVENT_ABILITY_PROGRESSION_RESULT = 111 --- (*integer* _reason_)
EVENT_ABILITY_PROGRESSION_XP_UPDATE = 111 --- (*luaindex* _progressionIndex_, *integer* _lastRankXP_, *integer* _nextRankXP_, *integer* _currentXP_, *bool* _atMorph_)
EVENT_ABILITY_REQUIREMENTS_FAIL = 111 --- (*integer* _errorId_)
EVENT_ACHIEVEMENTS_UPDATED = 111 
EVENT_ACHIEVEMENT_AWARDED = 111 --- (*string* _name_, *integer* _points_, *integer* _id_, *string* _link_)
EVENT_ACHIEVEMENT_UPDATED = 111 --- (*integer* _id_)
EVENT_ACTION_SLOTS_FULL_UPDATE = 111 --- (*bool* _isHotbarSwap_)
EVENT_ACTION_SLOT_ABILITY_SLOTTED = 111 --- (*bool* _newAbilitySlotted_)
EVENT_ACTION_SLOT_STATE_UPDATED = 111 --- (*luaindex* _slotNum_)
EVENT_ACTION_SLOT_UPDATED = 111 --- (*luaindex* _slotNum_)
EVENT_ACTION_UPDATE_COOLDOWNS = 111 
EVENT_ACTIVE_MOUNT_CHANGED = 111 
EVENT_ACTIVE_QUEST_TOOL_CHANGED = 111 --- (*luaindex* _journalIndex_, *luaindex* _toolIndex_)
EVENT_ACTIVE_QUEST_TOOL_CLEARED = 111 
EVENT_ACTIVE_QUICKSLOT_CHANGED = 111 --- (*integer* _slotId_)
EVENT_ACTIVE_WEAPON_PAIR_CHANGED = 111 --- (*integer* _activeWeaponPair_, *bool* _locked_)
EVENT_AGENT_CHAT_ACCEPTED = 111 
EVENT_AGENT_CHAT_DECLINED = 111 
EVENT_AGENT_CHAT_FORCED = 111 
EVENT_AGENT_CHAT_REQUESTED = 111 
EVENT_AGENT_CHAT_TERMINATED = 111 
EVENT_ALLIANCE_POINT_UPDATE = 111 --- (*integer* _alliancePoints_, *bool* _playSound_, *integer* _difference_)
EVENT_ARTIFACT_CONTROL_STATE = 111 --- (*string* _artifactName_, *integer* _keepId_, *string* _playerName_, *integer* _playerAlliance_, *integer* _controlEvent_, *integer* _controlState_, *integer* _campaignId_)
EVENT_ASSIGNED_CAMPAIGN_CHANGED = 111 --- (*integer* _newAssignedCampaignId_)
EVENT_ATTRIBUTE_FORCE_RESPEC = 111 --- (*string* _note_)
EVENT_ATTRIBUTE_UPGRADE_UPDATED
EVENT_AVENGE_KILL = 111 --- (*string* _avengedPlayerName_, *string* _killedPlayerName_)
EVENT_BANKED_MONEY_UPDATE = 111 --- (*integer* _newBankedMoney_, *integer* _oldBankedMoney_)
EVENT_BANK_IS_FULL = 111 
EVENT_BATTLE_STANDARDS_UPDATED = 111 
EVENT_BEGIN_LOCKPICK = 111 
EVENT_BEGIN_SIEGE_CONTROL = 111 
EVENT_BEGIN_SIEGE_UPGRADE = 111 
EVENT_BOSSES_CHANGED = 111 
EVENT_BROADCAST = 111 --- (*string* _message_)
EVENT_BUYBACK_RECEIPT = 111 --- (*string* _itemLink_, *integer* _itemQuantity_, *integer* _money_, *integer* _itemSoundCategory_)
EVENT_BUY_RECEIPT = 111 --- (*string* _entryName_, *integer* _entryType_, *integer* _entryQuantity_, *integer* _money_, *integer* _specialCurrencyType1_, *string* _specialCurrencyInfo1_, *integer* _specialCurrencyQuantity1_, *integer* _specialCurrencyType2_, *string* _specialCurrencyInfo2_, *integer* _specialCurrencyQuantity2_, *integer* _itemSoundCategory_)
EVENT_CAMPAIGN_ASSIGNMENT_RESULT = 111 --- (*integer* _result_)
EVENT_CAMPAIGN_EMPEROR_CHANGED = 111 --- (*integer* _campaignId_)
EVENT_CAMPAIGN_HISTORY_WINDOW_CHANGED = 111 
EVENT_CAMPAIGN_LEADERBOARD_DATA_CHANGED = 111 
EVENT_CAMPAIGN_QUEUE_JOINED = 111 --- (*integer* _campaignId_, *bool* _isGroup_)
EVENT_CAMPAIGN_QUEUE_LEFT = 111 --- (*integer* _campaignId_, *bool* _isGroup_)
EVENT_CAMPAIGN_QUEUE_POSITION_CHANGED = 111 --- (*integer* _campaignId_, *bool* _isGroup_, *integer* _position_)
EVENT_CAMPAIGN_QUEUE_STATE_CHANGED = 111 --- (*integer* _campaignId_, *bool* _isGroup_, *integer* _state_)
EVENT_CAMPAIGN_SCORE_DATA_CHANGED = 111 
EVENT_CAMPAIGN_SELECTION_DATA_CHANGED = 111 
EVENT_CAMPAIGN_STATE_INITIALIZED = 111 --- (*integer* _campaignId_)
EVENT_CAMPAIGN_UNDERPOP_BONUS_CHANGE_NOTIFICATION = 111 --- (*integer* _campaignId_)
EVENT_CANCEL_MOUSE_REQUEST_DESTROY_ITEM = 111 
EVENT_CANNOT_DO_THAT_WHILE_DEAD = 111 
EVENT_CANNOT_FISH_WHILE_SWIMMING = 111 
EVENT_CAPTURE_AREA_STATUS = 111 --- (*integer* _keepId_, *integer* _objectiveId_, *integer* _battlegroundContext_, *integer* _capturePoolValue_, *integer* _capturePoolMax_, *integer* _capturingPlayers_, *integer* _contestingPlayers_, *integer* _owningAlliance_)
EVENT_CHAMPION_POINT_GAINED = 111 
EVENT_CHAMPION_PURCHASE_RESULT = 111 --- (*integer* _result_)
EVENT_CHAMPION_SYSTEM_UNLOCKED = 111 
EVENT_CHATTER_BEGIN = 111 --- (*integer* _optionCount_)
EVENT_CHATTER_END = 111 
EVENT_CHAT_CHANNEL_INVITE = 111 --- (*string* _channelName_, *string* _playerName_)
EVENT_CHAT_CHANNEL_JOIN = 111 --- (*integer* _channelId_, *integer* _customChannelId_, *string* _channelName_)
EVENT_CHAT_CHANNEL_LEAVE = 111 --- (*integer* _channelId_, *integer* _customChannelId_, *string* _channelName_)
EVENT_CHAT_LOG_TOGGLED = 111 --- (*bool* _opened_)
EVENT_CHAT_MESSAGE_CHANNEL = 111 --- (*integer* _messageType_, *string* _fromName_, *string* _text_, *bool* _isCustomerService_)
EVENT_CLOSE_BANK = 111 
EVENT_CLOSE_FENCE = 111 
EVENT_CLOSE_GUILD_BANK = 111 
EVENT_CLOSE_STORE = 111 
EVENT_CLOSE_TRADING_HOUSE = 111 
EVENT_COLLECTIBLES_SEARCH_RESULTS_READY = 111 
EVENT_COLLECTIBLE_NOTIFICATION_NEW = 111 
EVENT_COLLECTIBLE_NOTIFICATION_REMOVED = 111 
EVENT_COLLECTIBLE_ON_COOLDOWN = 111 
EVENT_COLLECTIBLE_RENAME_ERROR = 111 --- (*integer* _errorReason_)
EVENT_COLLECTION_UPDATED = 111 
EVENT_COMBAT_EVENT = 111 --- (*integer* _result_, *bool* _isError_, *string* _abilityName_, *integer* _abilityGraphic_, *integer* _abilityActionSlotType_, *string* _sourceName_, *integer* _sourceType_, *string* _targetName_, *integer* _targetType_, *integer* _hitValue_, *integer* _powerType_, *integer* _damageType_, *bool* _log_)
EVENT_CONFIRM_INTERACT = 111 --- (*string* _dialogTitle_, *string* _dialogBody_, *string* _acceptText_, *string* _cancelText_)
EVENT_CONVERSATION_FAILED_INVENTORY_FULL = 111 
EVENT_CONVERSATION_FAILED_UNIQUE_ITEM = 111 
EVENT_CONVERSATION_UPDATED = 111 --- (*string* _conversationBodyText_, *integer* _conversationOptionCount_)
EVENT_CORONATE_EMPEROR_NOTIFICATION = 111 --- (*integer* _campaignId_, *string* _emperorName_, *integer* _emperorAlliance_)
EVENT_CRAFTING_STATION_INTERACT = 111 --- (*integer* _craftSkill_, *bool* _sameStation_)
EVENT_CRAFT_COMPLETED = 111 --- (*integer* _craftSkill_)
EVENT_CRAFT_STARTED = 111 --- (*integer* _craftSkill_)
EVENT_CURRENT_CAMPAIGN_CHANGED = 111 --- (*integer* _newCurrentCampaignId_)
EVENT_CURSOR_DROPPED = 111 --- (*integer* _type_, *integer* _param1_, *integer* _param2_, *integer* _param3_, *integer* _param4_, *integer* _param5_, *integer* _param6_)
EVENT_CURSOR_PICKUP = 111 --- (*integer* _type_, *integer* _param1_, *integer* _param2_, *integer* _param3_, *integer* _param4_, *integer* _param5_, *integer* _param6_, *integer* _itemSoundCategory_)
EVENT_DEPOSE_EMPEROR_NOTIFICATION = 111 --- (*integer* _campaignId_, *string* _emperorName_, *integer* _emperorAlliance_, *bool* _abdication_)
EVENT_DIFFICULTY_LEVEL_CHANGED = 111 --- (*integer* _difficultyLevel_)
EVENT_DISABLE_SIEGE_AIM_ABILITY = 111 
EVENT_DISABLE_SIEGE_FIRE_ABILITY = 111 
EVENT_DISABLE_SIEGE_PACKUP_ABILITY = 111 
EVENT_DISCOVERY_EXPERIENCE = 111 --- (*string* _areaName_, *integer* _level_, *integer* _previousExperience_, *integer* _currentExperience_, *integer* _rank_, *integer* _previousPoints_, *integer* _currentPoints_)
EVENT_DISGUISE_STATE_CHANGED = 111 --- (*string* _unitTag_, *integer* _disguiseState_)
EVENT_DISPLAY_ACTIVE_COMBAT_TIP = 111 --- (*integer* _activeCombatTipId_)
EVENT_DISPLAY_ANNOUNCEMENT = 111 --- (*string* _title_, *string* _description_)
EVENT_DISPLAY_TUTORIAL = 111 --- (*luaindex* _tutorialIndex_)
EVENT_DISPOSITION_UPDATE = 111 --- (*string* _unitTag_)
EVENT_DYEING_STATION_INTERACT_END = 111 
EVENT_DYEING_STATION_INTERACT_START = 111 
EVENT_EFFECTS_FULL_UPDATE = 111 
EVENT_EFFECT_CHANGED = 111 --- (*integer* _changeType_, *integer* _effectSlot_, *string* _effectName_, *string* _unitTag_, *number* _beginTime_, *number* _endTime_, *integer* _stackCount_, *string* _iconName_, *string* _buffType_, *integer* _effectType_, *integer* _abilityType_, *integer* _statusEffectType_)
EVENT_ENABLE_SIEGE_AIM_ABILITY = 111 
EVENT_ENABLE_SIEGE_FIRE_ABILITY = 111 
EVENT_ENABLE_SIEGE_PACKUP_ABILITY = 111 
EVENT_END_CRAFTING_STATION_INTERACT = 111 
EVENT_END_FAST_TRAVEL_INTERACTION = 111 
EVENT_END_FAST_TRAVEL_KEEP_INTERACTION = 111 
EVENT_END_KEEP_GUILD_CLAIM_INTERACTION = 111 
EVENT_END_KEEP_GUILD_RELEASE_INTERACTION = 111 
EVENT_END_SIEGE_CONTROL = 111 
EVENT_END_SOUL_GEM_RESURRECTION = 111 
EVENT_ENLIGHTENED_STATE_GAINED = 111 
EVENT_ENLIGHTENED_STATE_LOST = 111 
EVENT_ENTER_GROUND_TARGET_MODE = 111 
EVENT_EXPERIENCE_GAIN = 111 --- (*integer* _reason_, *integer* _level_, *integer* _previousExperience_, *integer* _currentExperience_)
EVENT_EXPERIENCE_UPDATE = 111 --- (*string* _unitTag_, *integer* _currentExp_, *integer* _maxExp_, *integer* _reason_)
EVENT_FAST_TRAVEL_KEEP_NETWORK_LINK_CHANGED = 111 --- (*luaindex* _linkIndex_, *integer* _linkType_, *integer* _owningAlliance_, *integer* _oldLinkType_, *integer* _oldOwningAlliance_, *bool* _isLocal_)
EVENT_FAST_TRAVEL_KEEP_NETWORK_UPDATED = 111 
EVENT_FAST_TRAVEL_NETWORK_UPDATED = 111 --- (*luaindex* _nodeIndex_)
EVENT_FEEDBACK_REQUESTED = 111 --- (*integer* _feedbackId_)
EVENT_FEEDBACK_TOO_FREQUENT_SCREENSHOT = 111 
EVENT_FINESSE_RANK_CHANGED = 111 --- (*string* _unitTag_, *luaindex* _rankNum_, *string* _name_, *integer* _xpBonus_, *bool* _loot_)
EVENT_FISHING_LURE_CLEARED = 111 
EVENT_FISHING_LURE_SET = 111 --- (*luaindex* _fishingLure_)
EVENT_FORWARD_CAMPS_UPDATED = 111 
EVENT_FORWARD_CAMP_RESPAWN_TIMER_BEGINS = 111 --- (*integer* _durationMS_)
EVENT_GAME_CAMERA_ACTIVATED = 111 
EVENT_GAME_CAMERA_DEACTIVATED = 111 
EVENT_GAME_CAMERA_UI_MODE_CHANGED = 111 
EVENT_GAME_FOCUS_CHANGED = 111 --- (*bool* _hasFocus_)
EVENT_GRAVEYARD_USAGE_FAILURE = 111 
EVENT_GROUPING_TOOLS_ERROR = 111 --- (*integer* _errorReason_)
EVENT_GROUPING_TOOLS_LFG_JOINED = 111 --- (*string* _locationName_)
EVENT_GROUPING_TOOLS_STATUS_UPDATE = 111 --- (*bool* _inQueue_)
EVENT_GROUP_CAMPAIGN_ASSIGNMENTS_CHANGED = 111 
EVENT_GROUP_INVITE_RECEIVED = 111 --- (*string* _inviterName_)
EVENT_GROUP_INVITE_REMOVED = 111 
EVENT_GROUP_INVITE_RESPONSE = 111 --- (*string* _inviterName_, *integer* _response_)
EVENT_GROUP_MEMBER_CONNECTED_STATUS = 111 --- (*string* _unitTag_, *bool* _isOnline_)
EVENT_GROUP_MEMBER_IN_REMOTE_REGION = 111 --- (*string* _unitTag_, *bool* _isInRemoteRegion_)
EVENT_GROUP_MEMBER_JOINED = 111 --- (*string* _memberName_)
EVENT_GROUP_MEMBER_LEFT = 111 --- (*string* _memberName_, *integer* _reason_, *bool* _wasLocalPlayer_, *bool* _amLeader_)
EVENT_GROUP_MEMBER_ROLES_CHANGED = 111 --- (*string* _unitTag_, *bool* _dps_, *bool* _healer_, *bool* _tank_)
EVENT_GROUP_NOTIFICATION_MESSAGE = 111 --- (*integer* _messageId_)
EVENT_GROUP_SUPPORT_RANGE_UPDATE = 111 --- (*string* _unitTag_, *bool* _status_)
EVENT_GROUP_TYPE_CHANGED = 111 --- (*bool* _largeGroup_)
EVENT_GROUP_UPDATE = 111 
EVENT_GUEST_CAMPAIGN_CHANGED = 111 --- (*integer* _newGuestCampaignId_)
EVENT_GUILD_BANKED_MONEY_UPDATE = 111 --- (*integer* _newBankedMoney_, *integer* _oldBankedMoney_)
EVENT_GUILD_BANK_DESELECTED = 111 
EVENT_GUILD_BANK_ITEMS_READY = 111 
EVENT_GUILD_BANK_ITEM_ADDED = 111 --- (*integer* _slotId_)
EVENT_GUILD_BANK_ITEM_REMOVED = 111 --- (*integer* _slotId_)
EVENT_GUILD_BANK_OPEN_ERROR = 111 --- (*integer* _reason_)
EVENT_GUILD_BANK_SELECTED = 111 --- (*integer* _guildId_)
EVENT_GUILD_BANK_TRANSFER_ERROR = 111 --- (*integer* _reason_)
EVENT_GUILD_BANK_UPDATED_QUANTITY = 111 --- (*integer* _slotId_)
EVENT_GUILD_KIOSK_CONSIDER_BID_START = 111 
EVENT_GUILD_KIOSK_CONSIDER_BID_STOP = 111 
EVENT_GUILD_KIOSK_CONSIDER_PURCHASE_START = 111 
EVENT_GUILD_KIOSK_CONSIDER_PURCHASE_STOP = 111 
EVENT_GUILD_KIOSK_ERROR = 111 --- (*integer* _reason_)
EVENT_HELP_INITIALIZED = 111 
EVENT_HELP_SEARCH_RESULTS_READY = 111 
EVENT_HERALDRY_CUSTOMIZATION_END = 111 
EVENT_HERALDRY_CUSTOMIZATION_START = 111 
EVENT_HERALDRY_FUNDS_UPDATED = 111 
EVENT_HERALDRY_SAVED = 111 
EVENT_HIDE_BOOK = 111 
EVENT_HIDE_OBJECTIVE_STATUS = 111 
EVENT_HOT_BAR_RESULT = 111 --- (*integer* _reason_)
EVENT_IMPACTFUL_HIT = 111 
EVENT_IMPERIAL_CITY_ACCESS_GAINED_NOTIFICATION = 111 --- (*integer* _campaignId_, *integer* _alliance_)
EVENT_IMPERIAL_CITY_ACCESS_LOST_NOTIFICATION = 111 --- (*integer* _campaignId_, *integer* _alliance_)
EVENT_INSTANCE_KICK_TIME_UPDATE = 111 --- (*integer* _timeRemainingMs_)
EVENT_INTERACTABLE_IMPOSSIBLE_TO_PICK = 111 --- (*string* _interactableName_)
EVENT_INTERACTABLE_LOCKED = 111 --- (*string* _interactableName_)
EVENT_INTERACT_BUSY = 111 
EVENT_INTERFACE_SETTING_CHANGED = 111 --- (*integer* _system_, *integer* _settingId_)
EVENT_INVENTORY_BOUGHT_BAG_SPACE = 111 --- (*integer* _numberOfSlots_)
EVENT_INVENTORY_BOUGHT_BANK_SPACE = 111 --- (*integer* _numberOfSlots_)
EVENT_INVENTORY_BUY_BAG_SPACE = 111 --- (*integer* _cost_)
EVENT_INVENTORY_BUY_BANK_SPACE = 111 --- (*integer* _cost_)
EVENT_INVENTORY_CLOSE_BUY_SPACE = 111 
EVENT_INVENTORY_FULL_UPDATE = 111 
EVENT_INVENTORY_IS_FULL = 111 --- (*integer* _numSlotsRequested_, *integer* _numSlotsFree_)
EVENT_INVENTORY_ITEM_DESTROYED = 111 --- (*integer* _itemSoundCategory_)
EVENT_INVENTORY_ITEM_USED = 111 --- (*integer* _itemSoundCategory_)
EVENT_INVENTORY_SINGLE_SLOT_UPDATE = 111 --- (*integer* _bagId_, *integer* _slotId_, *bool* _isNewItem_, *integer* _itemSoundCategory_, *integer* _updateReason_)
EVENT_INVENTORY_SLOT_LOCKED = 111 --- (*integer* _bagId_, *integer* _slotId_)
EVENT_INVENTORY_SLOT_UNLOCKED = 111 --- (*integer* _bagId_, *integer* _slotId_)
EVENT_ITEM_LAUNDER_RESULT = 111 --- (*integer* _result_)
EVENT_ITEM_ON_COOLDOWN = 111 
EVENT_ITEM_REPAIR_FAILURE = 111 --- (*integer* _reason_)
EVENT_ITEM_SLOT_CHANGED = 111 --- (*integer* _itemSoundCategory_)
EVENT_JUMP_FAILED = 111 --- (*integer* _reason_)
EVENT_JUSTICE_BOUNTY_PAYOFF_AMOUNT_UPDATED = 111 --- (*integer* _oldBounty_, *integer* _newBounty_)
EVENT_JUSTICE_FENCE_UPDATE = 111 --- (*integer* _sellsUsed_, *integer* _laundersUsed_)
EVENT_JUSTICE_GOLD_PICKPOCKETED = 111 --- (*integer* _goldAmount_)
EVENT_JUSTICE_GOLD_REMOVED = 111 --- (*integer* _goldAmount_)
EVENT_JUSTICE_INFAMY_UPDATED = 111 --- (*integer* _oldInfamy_, *integer* _newInfamy_, *integer* _oldInfamyLevel_, *integer* _newInfamyLevel_)
EVENT_JUSTICE_ITEM_PICKPOCKETED = 111 --- (*string* _itemName_, *integer* _itemCount_)
EVENT_JUSTICE_LIVESTOCK_SLAIN = 111 
EVENT_JUSTICE_NOW_KOS = 111 
EVENT_JUSTICE_NO_LONGER_KOS = 111 
EVENT_JUSTICE_NPC_SHUNNING = 111 
EVENT_JUSTICE_PICKPOCKET_FAILED = 111 
EVENT_JUSTICE_STOLEN_ITEMS_REMOVED = 111 
EVENT_KEEPS_INITIALIZED = 111 
EVENT_KEEP_ALLIANCE_OWNER_CHANGED = 111 --- (*integer* _keepId_, *integer* _battlegroundContext_, *integer* _owningAlliance_)
EVENT_KEEP_END_INTERACTION = 111 
EVENT_KEEP_GATE_STATE_CHANGED = 111 --- (*integer* _keepId_, *bool* _open_)
EVENT_KEEP_GUILD_CLAIM_UPDATE = 111 --- (*integer* _keepId_, *integer* _battlegroundContext_)
EVENT_KEEP_INITIALIZED = 111 --- (*integer* _keepId_, *integer* _battlegroundContext_)
EVENT_KEEP_OWNERSHIP_CHANGED_NOTIFICATION = 111 --- (*integer* _campaignId_, *integer* _keepId_, *integer* _oldOwner_, *integer* _newOwner_)
EVENT_KEEP_RESOURCE_UPDATE = 111 --- (*integer* _keepId_)
EVENT_KEEP_START_INTERACTION = 111 
EVENT_KEEP_UNDER_ATTACK_CHANGED = 111 --- (*integer* _keepId_, *integer* _battlegroundContext_, *bool* _underAttack_)
EVENT_KILL_LOCATIONS_UPDATED = 111 
EVENT_LEADER_UPDATE = 111 --- (*string* _leaderTag_)
EVENT_LEAVE_CAMPAIGN_QUEUE_RESPONSE = 111 --- (*integer* _response_)
EVENT_LEAVE_RAM_ESCORT = 111 
EVENT_LEVEL_UPDATE = 111 --- (*string* _unitTag_, *integer* _level_)
EVENT_LINKED_WORLD_POSITION_CHANGED = 111 
EVENT_LOCKPICK_BROKE = 111 --- (*integer* _inactivityLengthMs_)
EVENT_LOCKPICK_FAILED = 111 
EVENT_LOCKPICK_SUCCESS = 111 
EVENT_LOGOUT_DEFERRED = 111 --- (*integer* _deferMilliseconds_, *bool* _quitRequested_)
EVENT_LOGOUT_DISALLOWED = 111 --- (*bool* _quitRequested_)
EVENT_LOOT_CLOSED = 111 
EVENT_LOOT_ITEM_FAILED = 111 --- (*integer* _reason_, *string* _itemName_)
EVENT_LOOT_RECEIVED = 111 --- (*string* _receivedBy_, *string* _itemName_, *integer* _quantity_, *integer* _itemSound_, *integer* _lootType_, *bool* _self_, *bool* _isPickpocketLoot_)
EVENT_LOOT_UPDATED = 111 
EVENT_LORE_BOOK_ALREADY_KNOWN = 111 --- (*string* _bookTitle_)
EVENT_LORE_BOOK_LEARNED = 111 --- (*luaindex* _categoryIndex_, *luaindex* _collectionIndex_, *luaindex* _bookIndex_, *luaindex* _guildIndex_)
EVENT_LORE_BOOK_LEARNED_SKILL_EXPERIENCE = 111 --- (*luaindex* _categoryIndex_, *luaindex* _collectionIndex_, *luaindex* _bookIndex_, *luaindex* _guildIndex_, *integer* _skillType_, *luaindex* _skillIndex_, *luaindex* _rank_, *integer* _previousXP_, *integer* _currentXP_)
EVENT_LORE_COLLECTION_COMPLETED = 111 --- (*luaindex* _categoryIndex_, *luaindex* _collectionIndex_, *luaindex* _guildIndex_)
EVENT_LORE_COLLECTION_COMPLETED_SKILL_EXPERIENCE = 111 --- (*luaindex* _categoryIndex_, *luaindex* _collectionIndex_, *luaindex* _guildIndex_, *integer* _skillType_, *luaindex* _skillIndex_, *luaindex* _rank_, *integer* _previousXP_, *integer* _currentXP_)
EVENT_LORE_LIBRARY_INITIALIZED = 111 
EVENT_MAIL_ATTACHED_MONEY_CHANGED = 111 --- (*integer* _moneyAmount_)
EVENT_MAIL_ATTACHMENT_ADDED = 111 --- (*luaindex* _attachmentSlot_)
EVENT_MAIL_ATTACHMENT_REMOVED = 111 --- (*luaindex* _attachmentSlot_)
EVENT_MAIL_CLOSE_MAILBOX = 111 
EVENT_MAIL_COD_CHANGED = 111 --- (*integer* _codAmount_)
EVENT_MAIL_INBOX_UPDATE = 111 
EVENT_MAIL_NUM_UNREAD_CHANGED = 111 --- (*integer* _numUnread_)
EVENT_MAIL_OPEN_MAILBOX = 111 
EVENT_MAIL_READABLE = 111 --- (*id64* _mailId_)
EVENT_MAIL_REMOVED = 111 --- (*id64* _mailId_)
EVENT_MAIL_SEND_FAILED = 111 --- (*integer* _reason_)
EVENT_MAIL_SEND_SUCCESS = 111 
EVENT_MAIL_TAKE_ATTACHED_ITEM_SUCCESS = 111 --- (*id64* _mailId_)
EVENT_MAIL_TAKE_ATTACHED_MONEY_SUCCESS = 111 --- (*id64* _mailId_)
EVENT_MAP_PING = 111 --- (*integer* _pingEventType_, *integer* _pingType_, *string* _pingTag_, *number* _offsetX_, *number* _offsetY_, *bool* _isLocalPlayerOwner_)
EVENT_MEDAL_AWARDED = 111 --- (*string* _name_, *string* _texture_, *string* _condition_)
EVENT_MISSING_LURE = 111 
EVENT_MONEY_UPDATE = 111 --- (*integer* _newMoney_, *integer* _oldMoney_, *integer* _reason_)
EVENT_MOUNTED_STATE_CHANGED = 111 --- (*bool* _mounted_)
EVENT_MOUNT_FAILURE = 111 --- (*integer* _reason_, *integer* _arg1_)
EVENT_MOUNT_INFO_UPDATED = 111 
EVENT_MOUSE_REQUEST_ABANDON_QUEST = 111 --- (*luaindex* _journalIndex_, *string* _name_)
EVENT_MOUSE_REQUEST_DESTROY_ITEM = 111 --- (*integer* _bagId_, *integer* _slotIndex_, *integer* _itemCount_, *string* _name_, *bool* _needsConfirm_)
EVENT_MOUSE_REQUEST_DESTROY_ITEM_FAILED = 111 --- (*integer* _bagId_, *integer* _slotIndex_, *integer* _itemCount_, *string* _name_, *integer* _reason_)
EVENT_NEW_MOVEMENT_IN_UI_MODE = 111 
EVENT_NON_COMBAT_BONUS_CHANGED = 111 --- (*integer* _nonCombatBonus_, *integer* _oldValue_, *integer* _newValue_)
EVENT_NOT_ENOUGH_MONEY = 111 
EVENT_NO_INTERACT_TARGET = 111 
EVENT_OBJECTIVES_UPDATED = 111 
EVENT_OBJECTIVE_COMPLETED = 111 --- (*luaindex* _zoneIndex_, *luaindex* _poiIndex_, *integer* _level_, *integer* _previousExperience_, *integer* _currentExperience_, *integer* _rank_, *integer* _previousPoints_, *integer* _currentPoints_)
EVENT_OBJECTIVE_CONTROL_STATE = 111 --- (*integer* _objectiveKeepId_, *integer* _objectiveObjectiveId_, *integer* _battlegroundContext_, *string* _objectiveName_, *integer* _objectiveType_, *integer* _objectiveControlEvent_, *integer* _objectiveControlState_, *integer* _objectiveParam1_, *integer* _objectiveParam2_)
EVENT_OPEN_BANK = 111 
EVENT_OPEN_FENCE = 111 
EVENT_OPEN_GUILD_BANK = 111 
EVENT_OPEN_STORE = 111 
EVENT_OPEN_TRADING_HOUSE = 111 
EVENT_PICKPOCKET_ON_COOLDOWN = 111 
EVENT_PICKPOCKET_OUT_OF_POSITION = 111 
EVENT_PICKPOCKET_STATE_UPDATED = 111 
EVENT_PICKPOCKET_SUSPICIOUS = 111 
EVENT_PICKPOCKET_TOO_FAR = 111 
EVENT_PLAYER_ACTIVATED = 111 
EVENT_PLAYER_ALIVE = 111 
EVENT_PLAYER_COMBAT_STATE = 111 --- (*bool* _inCombat_)
EVENT_PLAYER_DEACTIVATED = 111 
EVENT_PLAYER_DEAD = 111 
EVENT_PLAYER_DEATH_INFO_UPDATE = 111 
EVENT_PLAYER_DEATH_REQUEST_FAILURE = 111 
EVENT_PLAYER_IN_PIN_AREA_CHANGED = 111 --- (*integer* _pinType_, *integer* _param1_, *integer* _param2_, *integer* _param3_, *bool* _playerIsInside_)
EVENT_PLAYER_NOT_SWIMMING = 111 
EVENT_PLAYER_SWIMMING = 111 
EVENT_PLAYER_TITLES_UPDATE = 111 
EVENT_PLEDGE_OF_MARA_OFFER = 111 --- (*string* _targetName_, *bool* _isSender_)
EVENT_PLEDGE_OF_MARA_OFFER_REMOVED = 111 
EVENT_PLEDGE_OF_MARA_RESULT = 111 --- (*integer* _reason_, *string* _targetName_)
EVENT_POIS_INITIALIZED = 111 
EVENT_POI_DISCOVERED = 111 --- (*luaindex* _zoneIndex_, *luaindex* _poiIndex_)
EVENT_POI_UPDATED = 111 --- (*luaindex* _zoneIndex_, *luaindex* _poiIndex_)
EVENT_POWER_UPDATE = 111 --- (*string* _unitTag_, *luaindex* _powerIndex_, *integer* _powerType_, *integer* _powerValue_, *integer* _powerMax_, *integer* _powerEffectiveMax_)
EVENT_PREFERRED_CAMPAIGN_CHANGED = 111 --- (*integer* _newPreferredCampaignId_)
EVENT_QUEST_ADDED = 111 --- (*luaindex* _journalIndex_, *string* _questName_, *string* _objectiveName_)
EVENT_QUEST_ADVANCED = 111 --- (*luaindex* _journalIndex_, *string* _questName_, *bool* _isPushed_, *bool* _isComplete_, *bool* _mainStepChanged_)
EVENT_QUEST_COMPLETE = 111 --- (*string* _questName_, *integer* _level_, *integer* _previousExperience_, *integer* _currentExperience_, *integer* _rank_, *integer* _previousPoints_, *integer* _currentPoints_)
EVENT_QUEST_COMPLETE_ATTEMPT_FAILED_INVENTORY_FULL = 111 
EVENT_QUEST_COMPLETE_DIALOG = 111 --- (*luaindex* _journalIndex_)
EVENT_QUEST_CONDITION_COUNTER_CHANGED = 111 --- (*luaindex* _journalIndex_, *string* _questName_, *string* _conditionText_, *integer* _conditionType_, *integer* _currConditionVal_, *integer* _newConditionVal_, *integer* _conditionMax_, *bool* _isFailCondition_, *string* _stepOverrideText_, *bool* _isPushed_, *bool* _isComplete_, *bool* _isConditionComplete_, *bool* _isStepHidden_)
EVENT_QUEST_LIST_UPDATED = 111 
EVENT_QUEST_LOG_IS_FULL = 111 
EVENT_QUEST_OFFERED = 111 
EVENT_QUEST_OPTIONAL_STEP_ADVANCED = 111 --- (*string* _text_)
EVENT_QUEST_POSITION_REQUEST_COMPLETE = 111 --- (*integer* _taskId_, *integer* _pinType_, *number* _xLoc_, *number* _yLoc_, *number* _areaRadius_, *bool* _insideCurrentMapWorld_, *bool* _isBreadcrumb_)
EVENT_QUEST_REMOVED = 111 --- (*bool* _isCompleted_, *luaindex* _journalIndex_, *string* _questName_, *luaindex* _zoneIndex_, *luaindex* _poiIndex_)
EVENT_QUEST_SHARED = 111 --- (*integer* _questId_)
EVENT_QUEST_SHARE_REMOVED = 111 --- (*integer* _questId_)
EVENT_QUEST_SHOW_JOURNAL_ENTRY = 111 --- (*luaindex* _journalIndex_)
EVENT_QUEST_TIMER_PAUSED = 111 --- (*luaindex* _journalIndex_, *bool* _isPaused_)
EVENT_QUEST_TIMER_UPDATED = 111 --- (*luaindex* _journalIndex_)
EVENT_QUEST_TOOL_UPDATED = 111 --- (*luaindex* _journalIndex_, *string* _questName_)
EVENT_QUEUE_FOR_CAMPAIGN_RESPONSE = 111 --- (*integer* _response_)
EVENT_RAID_LEADERBOARD_DATA_CHANGED = 111 
EVENT_RAID_LEADERBOARD_PLAYER_DATA_CHANGED = 111 
EVENT_RAID_PARTICIPATION_UPDATE = 111 
EVENT_RAID_REVIVE_COUNTER_UPDATE = 111 --- (*integer* _currentCounter_)
EVENT_RAID_SCORE_NOTIFICATION_ADDED = 111 --- (*integer* _notificationId_)
EVENT_RAID_SCORE_NOTIFICATION_REMOVED = 111 --- (*integer* _notificationId_)
EVENT_RAID_TIMER_STATE_UPDATE = 111 
EVENT_RAID_TRIAL_COMPLETE = 111 --- (*string* _trialName_, *integer* _score_, *integer* _totalTime_)
EVENT_RAID_TRIAL_FAILED = 111 --- (*string* _trialName_, *integer* _score_)
EVENT_RAID_TRIAL_NEW_BEST_SCORE = 111 --- (*string* _trialName_, *integer* _score_, *bool* _weekly_)
EVENT_RAID_TRIAL_SCORE_UPDATE = 111 --- (*integer* _scoreType_, *integer* _scoreAmount_, *integer* _totalScore_)
EVENT_RAID_TRIAL_STARTED = 111 --- (*string* _trialName_, *bool* _weekly_)
EVENT_RAM_ESCORT_COUNT_UPDATE = 111 --- (*integer* _numEscorts_)
EVENT_RANK_POINT_UPDATE = 111 --- (*string* _unitTag_, *integer* _rankPoints_, *integer* _difference_)
EVENT_RECIPE_ALREADY_KNOWN = 111 
EVENT_RECIPE_LEARNED = 111 --- (*luaindex* _recipeListIndex_, *luaindex* _recipeIndex_)
EVENT_REMOVE_ACTIVE_COMBAT_TIP = 111 --- (*integer* _activeCombatTipId_, *integer* _result_)
EVENT_REMOVE_TUTORIAL = 111 --- (*luaindex* _tutorialIndex_)
EVENT_REQUIREMENTS_FAIL = 111 --- (*integer* _errorId_)
EVENT_RESURRECT_FAILURE = 111 --- (*string* _targetName_, *integer* _reason_)
EVENT_RESURRECT_REQUEST = 111 --- (*string* _requester_, *integer* _timeLeftToAccept_)
EVENT_RESURRECT_REQUEST_REMOVED = 111 
EVENT_RETICLE_HIDDEN_UPDATE = 111 --- (*bool* _hidden_)
EVENT_RETICLE_TARGET_CHANGED = 111 
EVENT_RETICLE_TARGET_PLAYER_CHANGED = 111 
EVENT_REVENGE_KILL = 111 --- (*string* _killedPlayerName_)
EVENT_SCREENSHOT_SAVED = 111 --- (*string* _directory_, *string* _filename_)
EVENT_SCRIPTED_WORLD_EVENT_INVITE = 111 --- (*integer* _eventId_, *string* _scriptedEventName_, *string* _inviterName_, *string* _questName_)
EVENT_SELL_RECEIPT = 111 --- (*string* _itemName_, *integer* _itemQuantity_, *integer* _money_)
EVENT_SERVER_SHUTDOWN_INFO = 111 --- (*integer* _action_, *integer* _timeRemaining_)
EVENT_SHOW_BOOK = 111 --- (*string* _bookTitle_, *string* _body_, *integer* _medium_, *bool* _showTitle_)
EVENT_SHOW_TREASURE_MAP = 111 --- (*luaindex* _treasureMapIndex_)
EVENT_SIEGE_BUSY = 111 --- (*string* _siegeName_)
EVENT_SIEGE_CONTROL_ANOTHER_PLAYER = 111 --- (*string* _siegeName_)
EVENT_SIEGE_CREATION_FAILED_CLOSEST_DOOR_ALREADY_HAS_RAM = 111 
EVENT_SIEGE_CREATION_FAILED_NO_VALID_DOOR = 111 
EVENT_SIEGE_FIRE_FAILED_COOLDOWN = 111 
EVENT_SIEGE_FIRE_FAILED_RETARGETING = 111 
EVENT_SIEGE_PACK_FAILED_INVENTORY_FULL = 111 
EVENT_SIEGE_PACK_FAILED_NOT_CREATOR = 111 
EVENT_SKILLS_FULL_UPDATE = 111 
EVENT_SKILL_FORCE_RESPEC = 111 --- (*string* _note_)
EVENT_SKILL_LINE_ADDED = 111 --- (*integer* _skillType_, *luaindex* _skillIndex_)
EVENT_SKILL_POINTS_CHANGED = 111 --- (*integer* _pointsBefore_, *integer* _pointsNow_, *integer* _partialPointsBefore_, *integer* _partialPointsNow_)
EVENT_SKILL_RANK_UPDATE = 111 --- (*integer* _skillType_, *luaindex* _skillIndex_, *luaindex* _rank_)
EVENT_SKILL_XP_UPDATE = 111 --- (*integer* _skillType_, *luaindex* _skillIndex_, *integer* _reason_, *luaindex* _rank_, *integer* _previousXP_, *integer* _currentXP_)
EVENT_SLOT_IS_LOCKED_FAILURE = 111 --- (*integer* _bagId_, *integer* _slotId_)
EVENT_SMITHING_TRAIT_RESEARCH_COMPLETED = 111 --- (*integer* _craftingSkillType_, *luaindex* _researchLineIndex_, *luaindex* _traitIndex_)
EVENT_SMITHING_TRAIT_RESEARCH_STARTED = 111 --- (*integer* _craftingSkillType_, *luaindex* _researchLineIndex_, *luaindex* _traitIndex_)
EVENT_SOUL_GEM_ITEM_CHARGE_FAILURE = 111 --- (*integer* _reason_)
EVENT_STABLE_INTERACT_END = 111 
EVENT_STABLE_INTERACT_START = 111 
EVENT_START_FAST_TRAVEL_INTERACTION = 111 --- (*luaindex* _nodeIndex_)
EVENT_START_FAST_TRAVEL_KEEP_INTERACTION = 111 --- (*integer* _keepId_)
EVENT_START_KEEP_GUILD_CLAIM_INTERACTION = 111 
EVENT_START_KEEP_GUILD_RELEASE_INTERACTION = 111 
EVENT_START_SOUL_GEM_RESURRECTION = 111 --- (*integer* _durationMs_)
EVENT_STATS_UPDATED = 111 --- (*string* _unitTag_)
EVENT_STEALTH_STATE_CHANGED = 111 --- (*string* _unitTag_, *integer* _stealthState_)
EVENT_STORE_FAILURE = 111 --- (*integer* _reason_)
EVENT_STUCK_BEGIN = 111 
EVENT_STUCK_CANCELED = 111 
EVENT_STUCK_COMPLETE = 111 
EVENT_STUCK_ERROR_ALREADY_IN_PROGRESS = 111 
EVENT_STUCK_ERROR_INVALID_LOCATION = 111 
EVENT_STUCK_ERROR_IN_COMBAT = 111 
EVENT_STUCK_ERROR_ON_COOLDOWN = 111 
EVENT_STYLE_LEARNED = 111 --- (*luaindex* _styleIndex_, *integer* _chapterIndex_)
EVENT_SYNERGY_ABILITY_CHANGED = 111 
EVENT_TARGET_CHANGED = 111 --- (*string* _unitTag_)
EVENT_TITLE_UPDATE = 111 --- (*string* _unitTag_)
EVENT_TRACKING_UPDATE = 111 
EVENT_TRADE_ACCEPT_FAILED_NOT_ENOUGH_MONEY = 111 
EVENT_TRADE_CANCELED = 111 --- (*string* _cancelerName_)
EVENT_TRADE_CONFIRMATION_CHANGED = 111 --- (*integer* _who_, *integer* _level_)
EVENT_TRADE_ELEVATION_FAILED = 111 --- (*integer* _reason_, *string* _itemName_)
EVENT_TRADE_FAILED = 111 --- (*integer* _reason_)
EVENT_TRADE_INVITE_ACCEPTED = 111 
EVENT_TRADE_INVITE_CANCELED = 111 
EVENT_TRADE_INVITE_CONSIDERING = 111 --- (*string* _inviter_)
EVENT_TRADE_INVITE_DECLINED = 111 
EVENT_TRADE_INVITE_FAILED = 111 --- (*integer* _reason_, *string* _name_)
EVENT_TRADE_INVITE_REMOVED = 111 
EVENT_TRADE_INVITE_WAITING = 111 --- (*string* _invitee_)
EVENT_TRADE_ITEM_ADDED = 111 --- (*integer* _who_, *luaindex* _tradeIndex_, *integer* _itemSoundCategory_)
EVENT_TRADE_ITEM_ADD_FAILED = 111 --- (*integer* _reason_, *string* _itemName_)
EVENT_TRADE_ITEM_REMOVED = 111 --- (*integer* _who_, *luaindex* _tradeIndex_, *integer* _itemSoundCategory_)
EVENT_TRADE_ITEM_UPDATED = 111 --- (*integer* _who_, *luaindex* _tradeIndex_)
EVENT_TRADE_MONEY_CHANGED = 111 --- (*integer* _who_, *integer* _money_)
EVENT_TRADE_SUCCEEDED = 111 
EVENT_TRADING_HOUSE_AWAITING_RESPONSE = 111 --- (*integer* _responseType_)
EVENT_TRADING_HOUSE_CONFIRM_ITEM_PURCHASE = 111 --- (*luaindex* _pendingPurchaseIndex_)
EVENT_TRADING_HOUSE_ERROR = 111 --- (*integer* _errorCode_)
EVENT_TRADING_HOUSE_OPERATION_TIME_OUT = 111 --- (*integer* _responseType_)
EVENT_TRADING_HOUSE_PENDING_ITEM_UPDATE = 111 --- (*integer* _slotId_, *bool* _isPending_)
EVENT_TRADING_HOUSE_RESPONSE_RECEIVED = 111 --- (*integer* _responseType_, *integer* _result_)
EVENT_TRADING_HOUSE_SEARCH_COOLDOWN_UPDATE = 111 --- (*integer* _cooldownMilliseconds_)
EVENT_TRADING_HOUSE_SEARCH_RESULTS_RECEIVED = 111 --- (*integer* _guildId_, *integer* _numItemsOnPage_, *integer* _currentPage_, *bool* _hasMorePages_)
EVENT_TRADING_HOUSE_STATUS_RECEIVED = 111 
EVENT_TRAIT_LEARNED = 111 --- (*string* _itemName_, *string* _itemTrait_)
EVENT_TRIAL_FEATURE_RESTRICTED = 111 --- (*integer* _restrictionType_)
EVENT_TUTORIAL_SYSTEM_ENABLED_STATE_CHANGED = 111 --- (*bool* _enabled_)
EVENT_UI_ERROR = 111 --- (*integer* _stringId_)
EVENT_UNIT_ATTRIBUTE_VISUAL_ADDED = 111 --- (*string* _unitTag_, *integer* _unitAttributeVisual_, *integer* _statType_, *integer* _attributeType_, *integer* _powerType_, *number* _value_, *number* _maxValue_)
EVENT_UNIT_ATTRIBUTE_VISUAL_REMOVED = 111 --- (*string* _unitTag_, *integer* _unitAttributeVisual_, *integer* _statType_, *integer* _attributeType_, *integer* _powerType_, *number* _value_, *number* _maxValue_)
EVENT_UNIT_ATTRIBUTE_VISUAL_UPDATED = 111 --- (*string* _unitTag_, *integer* _unitAttributeVisual_, *integer* _statType_, *integer* _attributeType_, *integer* _powerType_, *number* _oldValue_, *number* _newValue_, *number* _oldMaxValue_, *number* _newMaxValue_)
EVENT_UNIT_CREATED = 111 --- (*string* _unitTag_)
EVENT_UNIT_DEATH_STATE_CHANGED = 111 --- (*string* _unitTag_, *bool* _isDead_)
EVENT_UNIT_DESTROYED = 111 --- (*string* _unitTag_)
EVENT_UNIT_FRAME_UPDATE = 111 --- (*string* _unitTag_)
EVENT_UNLOCKED_DYES_UPDATED = 111 
EVENT_UNSPENT_CHAMPION_POINTS_CHANGED = 111 
EVENT_UPDATE_BUYBACK = 111 
EVENT_VETERAN_DIFFICULTY_CHANGED = 111 --- (*string* _unitTag_, *bool* _isDifficult_)
EVENT_VETERAN_POINTS_GAIN = 111 --- (*integer* _reason_, *integer* _rank_, *integer* _previousPoints_, *integer* _currentPoints_)
EVENT_VETERAN_POINTS_UPDATE = 111 --- (*string* _unitTag_, *integer* _currentPoints_, *integer* _maxPoints_, *integer* _reason_)
EVENT_VETERAN_RANK_UPDATE = 111 --- (*string* _unitTag_, *integer* _rank_)
EVENT_VIBRATION = 111 --- (*integer* _duration_, *number* _coarseMotor_, *number* _fineMotor_, *number* _leftTriggerMotor_, *number* _rightTriggerMotor_)
EVENT_WEAPON_SWAP_LOCKED = 111 --- (*integer* _swapLevel_)
EVENT_WEREWOLF_STATE_CHANGED = 111 --- (*bool* _werewolf_)
EVENT_ZONE_CHANGED = 111 --- (*string* _zoneName_, *string* _subZoneName_, *bool* _newSubzone_)
EVENT_ZONE_CHANNEL_CHANGED = 111 
EVENT_ZONE_SCORING_CHANGED = 111 
EVENT_ZONE_UPDATE = 111 --- (*string* _unitTag_, *string* _newZoneName_)
EVENT_ACTION_LAYER_POPPED = 111 --- (*luaindex* _layerIndex_, *luaindex* _activeLayerIndex_)
EVENT_ACTION_LAYER_PUSHED = 111 --- (*luaindex* _layerIndex_, *luaindex* _activeLayerIndex_)
EVENT_ADD_ON_LOADED = 111 --- (*string* _addonName_)
EVENT_CAPS_LOCK_STATE_CHANGED = 111 --- (*bool* _capsLockEnabled_)
EVENT_GAMEPAD_PREFERRED_MODE_CHANGED = 111 --- (*bool* _gamepadPreferred_)
EVENT_GLOBAL_MOUSE_DOWN = 111 --- (*integer* _button_, *bool* _ctrl_, *bool* _alt_, *bool* _shift_, *bool* _command_)
EVENT_GLOBAL_MOUSE_UP = 111 --- (*integer* _button_, *bool* _ctrl_, *bool* _alt_, *bool* _shift_, *bool* _command_)
EVENT_GUI_HIDDEN = 111 --- (*string* _guiName_, *bool* _hidden_)
EVENT_INPUT_LANGUAGE_CHANGED = 111 
EVENT_KEYBINDINGS_LOADED = 111 
EVENT_KEYBINDING_CLEARED = 111 --- (*luaindex* _layerIndex_, *luaindex* _categoryIndex_, *luaindex* _actionIndex_, *luaindex* _bindingIndex_)
EVENT_KEYBINDING_SET = 111 --- (*luaindex* _layerIndex_, *luaindex* _categoryIndex_, *luaindex* _actionIndex_, *luaindex* _bindingIndex_, *integer* _keyCode_, *integer* _mod1_, *integer* _mod2_, *integer* _mod3_, *integer* _mod4_)
EVENT_LUA_ERROR = 111 --- (*string* _error_)
EVENT_LUA_LOW_MEMORY = 111 
EVENT_SCREEN_RESIZED = 111 --- (*integer* _x_, *integer* _y_)
EVENT_SCRIPT_ACCESS_VIOLATION = 111 --- (*string* _protectedFunctionName_)
EVENT_SECURE_RENDER_MODE_CHANGED = 111 --- (*bool* _enabled_)
EVENT_SHOW_GUI = 111 --- (*string* _guiName_, *string* _desiredStateName_)
EVENT_UPDATE_GUI_LOADING_PROGRESS = 111 --- (*string* _guiName_, *integer* _assetsLoaded_, *integer* _assetsTotal_)