std = "max+busted+eso"
stds.eso = {
    globals = {
        "AddMenuItem",
        "CALLBACK_MANAGER",
        "ClearMenu",
        "ClearTooltip",
        "Clock_TST",
        "CLOCK_TST_MENU",
        "Clock_TST_Moon",
        "Clock_TST_Moon",
        "Clock_TST_Moon_Masser",
        "Clock_TST_Time",
        "EVENT_ADD_ON_LOADED",
        "EVENT_MANAGER",
        "EVENT_PLAYER_COMBAT_STATE",
        "GAME_MENU_SCENE",
        "GetCVar",
        "GetControl",
        "GetDateStringFromTimestamp",
        "GetSecondsSinceMidnight",
        "GetTST",
        "GetTimeStamp",
        "GetTimeString",
        "GetWorldName",
        "GuiRoot",
        "HUD_SCENE",
        "HUD_UI_SCENE",
        "InformationTooltip",
        "InitializeTooltip",
        "LibAddonMenu2",
        "LibClockTST",
        "LibFeedback",
        "SLASH_COMMANDS",
        "SetTooltipText",
        "ShowMenu",
        "TIME_FORMAT_PRECISION_TWELVE_HOUR",
        "TIME_FORMAT_PRECISION_TWENTY_FOUR_HOUR",
        "TIME_FORMAT_PRECISION_TWENTY_FOUR_HOUR",
        "TIME_FORMAT_STYLE_CLOCK_TIME",
        "TOP",
        "WORLD_MAP_SCENE",
        "ZO_ColorDef",
        "ZO_FormatTime",
        "ZO_HUDFadeSceneFragment",
        "ZO_HUDFadeSceneFragment",
        "ZO_ONE_MONTH_IN_SECONDS",
        "ZO_ONE_YEAR_IN_SECONDS",
        "ZO_Object",
        "ZO_SavedVars",
        "d",
        "zo_strformat"
    },
}
self = false
exclude_files = {
    "Test/ZOMock.lua",
}
include_files = {
    "Asset/**/*.lua",
    "Lib/**/*.lua",
    "Test/**/*.lua"
}